### ISSUE TITLE
url shortner

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#1]
Nice job...

Would like an option for url shortner

**Comment by RebelCodeBase** [comment]
What URL shortener do you use and why do you use it? Do you use different ones?

**Comment by rinzes** [comment]
I use the tinyurl one. It make for a better uncluttered screen. This is from my OLD rss.py

import tinyurl

```
/# create message for new entry
  turl = tinyurl.create_one(entry.link)
      message = u"[\x02{0}\x02] \x02{1}\x02 {2}".format(
        colour_text(feed.name, feed.fg, feed.bg), entry.title, turl)
```

**Comment by RebelCodeBase** [comment]
This should be implemented on a per feed basis. For example, we could add "u" to a format string to invoke the url shortener (the default one or a configurable one). Seems reasonable to me.

**Comment by rinzes** [comment]
Sounds good to me

**Comment by RebelCodeBase** [comment]
Could you please have a look at this branch?
https://github.com/RebelCodeBase/sopel-rss/tree/issue_1_url_shortener
You should be able to set field y in the format string in order to invoke tinyurl.com links. I've implemented that on my own in order to minimize the dependencies.

**Comment by rinzes** [comment]
I think we have a problem with the following portion of the code

 ``def get_tinyurl(self, url):
        tinyurlapi = 'https://tinyurl.com/api-create.php'
        data = urllib.parse.urlencode({'url': url}).encode("utf-8")
        req = urllib.request.Request(tinyurlapi, data)
        response = urllib.request.urlopen(req)
        tinyurl = response.read().decode('utf-8')
        return tinyurl

I get the following error :

Error loading rss: 'utf-8' codec can't decode byte 0xab in position 24274: invalid start byte (../../codecs.py:313)

**Comment by RebelCodeBase** [comment]
I've obviously tested this with "my" rss feeds and it works. Could you please provide more debugging data? Which feed gives that error? Which format do you use? In short: please provide the output of .rss list <feedname> (and redact the channel if you like).

**Comment by rinzes** [comment]
My system is Debian 8.3 32 bit and the rss..py failed to load with that error. I also tried it on a Ubuntu 15.10 64 bit and get the same error.

**Comment by rinzes** [comment]
II must of did something wrong when I did copy/paste. I download direct and its now working. SORRY

**Comment by RebelCodeBase** [comment]
When you copy and paste it's a good idea to use the [raw view (master branch)](https://raw.githubusercontent.com/RebelCodeBase/sopel-rss/master/rss.py).
I will merge this into master then.
