### ISSUE TITLE
formats not being overriden

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#13]
The formats I have set are not being over-riding the default settings.

<dutch> .rss config formats
<Sopel> fl+fty,fl+ftl

[11:13] <Sopel> [IPO] Yum Picks Financial Partners Primavera And Ant for China Spin-Off → http://seekingalpha.com/article/4004397-yum-picks-financial-partners-primavera-ant-china-spin?source=feed_tag_ipo_analysis

If I manually add to the cfg file it still does not work. I have to set the defaults to fl+fty in the RSS.py to have it work with the url shortner

**Comment by rinzes** [comment]
When I started adding some new feeds it started working. Strange

**Comment by RebelCodeBase** [comment]
Right, thanks for the bug report!

**Comment by rinzes** [comment]
Still not working bud.. Now I get no response from

.rss config format

and when I do .rss config format fl+fty it still does not change settings or writes to cfg file

**Comment by RebelCodeBase** [comment]
The command is .rss config formats (with an s). It's about the default formats which can be more than one.
A different command is .rss format (without an s). It's about the format of one specific feed.

**Comment by rinzes** [comment]
OOPS.. sorry about that. All is ok now

**Comment by RebelCodeBase** [comment]
No it's ok to report that. It shows that there is a problem. Maybe not a technical one but an interface one. I am going to refactor this...
