### ISSUE TITLE
error loading rss.py module

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#15]
Error in rss setup procedure: say() missing 1 required positional argument: 'recipient' (../../../../../.sopel/modules/rss.py:518)

**Comment by rinzes** [comment]
I fixed the above by removing all the rss config
[rss]
feeds =
formats = 
templates =

with all the changes figured start anew :)

**Comment by RebelCodeBase** [comment]
The "meaningful error message" I suggested in #12 caused this error. sopel's current logging module is less than optimal so I removed it.
