### ISSUE TITLE
ERROR Unable to read

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#18]
ERROR:sopel.modules.rss:unable to read url "http://www.aljazeera.com/xml/rss/all.xml" of feed "Al_Jazeera"

ERROR:sopel.modules.rss:unable to read url "http://www.arrl.org/news/rss" of feed "ARRL"

ERROR:sopel.modules.rss:unable to read url "http://hosted.ap.org/lineups/SCIENCEHEADS.rss?SITE=AP&SECTION=HOME" of feed "AP_Science"
ERROR:sopel.modules.rss:unable to read url "http://www.frontpagemag.com/point/rss.xml" of feed "FrontPageMag"

**Comment by rinzes** [comment]
Must of been a fluke.. will continue to monitor

**Comment by RebelCodeBase** [comment]
Obviously, I've been too aggressive in checking the feeds. Please reopen if the error persists.

**Comment by rinzes** [comment]
ERROR:sopel.modules.rss3:unable to read url "http://feed.zacks.com/commentary/BearOfTheDay/rss" of feed "Zack_Bear"
ERROR:sopel.modules.rss3:unable to read url "http://feed.zacks.com/commentary/BullOfTheDay/rss" of feed "Zack_Bull"

**Comment by RebelCodeBase** [comment]
I cannot reproduce the problem:

.rss add #sopel-test Zack_Bull http://feed.zacks.com/commentary/BullOfTheDay/rss
[ <![CDATA[Zacks Investment Research - Bull of the Day]]> ] - feed.zacks.com
added rss feed "Zack_Bull" to channel "#sopel-test" with url "http://feed.zacks.com/commentary/BullOfTheDay/rss"
.rss get Zack_Bull
[Zack_Bull] Bull of the Day: Gibraltar Industries (ROCK) → http://www.zacks.com/commentary/89371/bull-of-the-day-gibraltar-industries-rock?cid=CS-ZC--89371
[Zack_Bull] Bull of the Day: Tillys (TLYS) → http://www.zacks.com/commentary/89433/bull-of-the-day-tillys-tlys?cid=CS-ZC--89433
[Zack_Bull] Bull of the Day: America's Car-Mart (CRMT) → http://www.zacks.com/commentary/89496/bull-of-the-day-americas-car-mart-crmt?cid=CS-ZC--89496
...
