### ISSUE TITLE
Post feed to more than one channel

### ISSUE THREAD

**Issue by kwaaak** [RebelCodeBase/sopel-rss#19]
Is it possible to post the same feed to more than one channel?
At the moment I can only add the feed again, and I have to use a different name for it.

**Comment by RebelCodeBase** [comment]
Right, that's the way it is at the moment and I it would be a big thing to change it. So nope, I don't think that there is an easy solution to add more than one channel to a feed.

But there is an easy workaround: just copy and paste the same line to the config file and name the feed slightly different (for example by addind the name of the channel if it is short enough).
