### ISSUE TITLE
Traceback Error: IndexError

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#2]
FWIW... I got the following when adding this feed..
https://feeds.feedburner.com/DiscoveryNews-Top-Stories

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/module.py", line 343, in guarded
    return function(bot, trigger, _args, *_kwargs)
  File "/home/znc/.sopel/modules/rss3.py", line 179, in rss
    __rss(bot, args)
  File "/home/znc/.sopel/modules/rss3.py", line 207, in __rss
    globals()[COMMANDS[cmd]['function']](bot, args)
  File "/home/znc/.sopel/modules/rss3.py", line 218, in __rssAdd
    checkresults = __feedCheck(bot, feedreader, channel, feedname)
  File "/home/znc/.sopel/modules/rss3.py", line 551, in __feedCheck
    item = feed['entries'][0]
IndexError: list index out of range

**Comment by RebelCodeBase** [comment]
There are two issues here:
(1) An error like this should be handled gracefully and a meaningful error message should be generated. I will fix this.
(2) The feed has no entries. See this ipython3 session:

In [1]: import feedparser

In [2]: feedparser.parse('https://feeds.feedburner.com/DiscoveryNews-Top-Stories')
Out[2]:
{'bozo': 1,
 'bozo_exception': xml.sax._exceptions.SAXParseException('not well-formed (invalid token)'),
 'encoding': 'UTF-8',
 **'entries': [],**
(...)

**Comment by RebelCodeBase** [comment]
Version 0.2.0 is out. It would be nice if you could install it. Please not: the format of "feeds" in the config file changed. You need to replace the spaces between channel, feed, url and format by pipes ("|").

**Comment by rinzes** [comment]
I used the DEFAULT format in the rss.py. Do I need to add the **format** in the cfg file

**Comment by RebelCodeBase** [comment]
Now, you can (and should) leave FORMAT_DEFAULT alone and use "formats" instead where you can define one or more custom default formats. For example, you can specify one format that you'd like to use but not all of you feeds have the necessary fields. Then a second best for those. At last, the global FORMAT_DEFAULT or a minimal default format will be used. Of course, you can override the format for each feed.

You can now also use "templates" to define you own custom templates (for example colors or braces or fancy unicode characters). You need not override all format strings only those that you'd like to change. 

I've also implemented an online help, for example: .rss custom define formats

I've written over 100 py.tests but of course, there might be bugs left. I'd be happy to fix them if you report the issues.

**Comment by rinzes** [comment]
thanks for all your hard work

**Comment by RebelCodeBase** [comment]
you are welcome. it's good to see that the module is used.
