### ISSUE TITLE
Color Format

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#9]
I'm having a heck of a time trying to config each feedname with diff colors in the .cfg file, Can you give me an example ie fl+f,?tl

**Comment by RebelCodeBase** [comment]
I am looking into that (and found a bug while doing so). I will write a section for the README.md and add some live feedback to .rss config templates.

**Comment by RebelCodeBase** [comment]
I've updated the project, please install the new version and try it out.

**Comment by rinzes** [comment]
the templates are not being saved to the config file. Stop/Start sopel losses the settings.

On 2nd look it appears it is now saving to the cfg file. strange it wasn't before

**Comment by RebelCodeBase** [comment]
I think you are right and I forgot to save the templates (at least in some cases). Please reopen if this happens again.
